### ISSUE TITLE
Wiki Page Home

### ISSUE THREAD

**Issue by xnanodax** [cscov/StarWarsBnb#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

# Comments:

**Comment by cscov** [comment]
Quick question: Am I going to be the one physically checking these off, or do I leave them for you to check off when I open a PA review issue?

**Comment by xnanodax** [comment]
I'll be checking them off :)! 

And this wiki page looks great!
