### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by xnanodax** [cscov/StarWarsBnb#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
# Comments:

**Comment by xnanodax** [comment]
Initial Proposal for this page has been reviewed. Please add other fields!

**Comment by cscov** [comment]
Finished my first draft! Please take a look :)

**Comment by cscov** [comment]
updated again after our chat

**Comment by xnanodax** [comment]
Awesome! Just need formatting (back ticking on column names)

**Comment by cscov** [comment]
updated
