### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by xnanodax** [cscov/StarWarsBnb#4]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

# Comments:

**Comment by xnanodax** [comment]
Initial Proposal for this page has been reviewed.

**Comment by cscov** [comment]
added first draft for review

**Comment by cscov** [comment]
updated after our chat yesterday

**Comment by xnanodax** [comment]
- [x] The current backend DELETE route for a booking doesn't have an id! How do you know which id to delete?
- [x] How would you add a booking?
- [x] You may not need the `/rooms/:id/reviews` if the reviews will automatically be fetched in a user show page. This design decision is up to you if you want to make the reviews a separate AJAX call from the the show page.

**Comment by cscov** [comment]
For now going to make a separate ajax calls for reviews at least until I get to that MVP. Booking routes have been updated
