### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by xnanodax** [cscov/StarWarsBnb#5]
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
# Comments:

**Comment by xnanodax** [comment]
Initial Proposal for this page has been reviewed. Please add the sample state!

**Comment by cscov** [comment]
first draft is ready for review

**Comment by cscov** [comment]
updated after our chat yesterday

**Comment by xnanodax** [comment]
Thanks Carolyn!

Update some formatting and we are good to go. Also in the spots, there are some keys that aren't aligned.
![screen shot 2018-04-06 at 9 21 05 am](https://user-images.githubusercontent.com/20424731/38432346-08d81a10-397c-11e8-898a-c23c4a9d2161.png)

**Comment by cscov** [comment]
updated, thanks!
