### ISSUE TITLE
Component Hierarchy with Wireframes

### ISSUE THREAD

**Issue by xnanodax** [cscov/StarWarsBnb#6]
# Component Hierarchy

- [x] All routes listed in the routes wiki page is also listed in the component hierarchy
- [x] Each component, if necessary, has route, state, and other components it renders [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy)
- [x] Necessary components are wrapped in a container
- [x] Correctly formatted
    - [x] Bullet point hierarchy
    - [x] Component names are displayed with `inline coding text` (backticks)
# Wireframes
- [x] Every component listed in the component hierarchy wiki page has at least one wireframe
- [x] Every MVPs listed on the MVP wiki page has at least one wireframe
- [x] Every route listed on the route wiki page has at least one wireframe
- [x] Contains Containers
- [x] Contains Lists
- [x] Contains ListItems
- [x] Correctly formatted
    - [x] Wireframe images display on the page
    - [x] Every wireframe has a header title

# Comments:

**Comment by xnanodax** [comment]
In general: 
- [x] I would double check on the name of your components so it follows React naming conventions and follows the single responsibility principle.
Example:
+ For the `SpotsSearch` predictive search, i would break components down from container -> index -> index items. I see container and one component nested under that does not follow this convention.
+ I would change `SpotsListItem` to `SpotsIndexItem` since the `SpotsIndex` is rendering these items.

Other Notable examples:
For the Search Results 
What do you mean by predictive search?

For Spots Search
There are more components than just the search bar. I would break it down from `SearchContainer` -> `SearchForm`

**Comment by cscov** [comment]
Thanks for catching the naming conventions. 
I tried to break search down a bit more, and by predictive search I meant that when you start typing in the search bar, it starts to dynamically filter search results based on what you type. Hopefully my new wireframe helps to illustrate this better. Ready for review!

**Comment by cscov** [comment]
updated after our conversation yesterday

**Comment by xnanodax** [comment]
I would add a route for the nav bar and session path.

Missing component hierarchy and views for 
1. `trips/:id` 
2. `trips/:id/edit`
