### ISSUE TITLE
User Authentication MVP

### ISSUE THREAD

**Issue by cscov** [cscov/StarWarsBnb#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route /#/oweiniouewbrviuwebv should redirect to either /, /login, or /signup
  - [x] Errors should display for both /signup and/login.
  - [x] Errors should clear when moving between /signup and /login.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by xnanodax** [comment]
Don't forget to check these off as you progress in this MVP! 
I suggest to use the list found [here](https://github.com/xnanodax/brainMap/issues/1). There are more details on what is going be to checked.

For your core 7 MVPs, you'll check them off as you go and assign me on the right hand side bar when an MVP is completed :)

**Comment by xnanodax** [comment]
Great styling, Carolyn!

When logging in or signing up, I can only type in the password fields.

**Comment by cscov** [comment]
Thanks, I think it's fixed now

**Comment by xnanodax** [comment]
Awesome! Great work!
